acceptance.bats, cmd/root.go, fixtures/int_or_string.yaml
Most of the fix was in updating the schemas to swap int-or-string for
oneOf. I've only updated the standalone schemas so far so switching
kubeval to use those for the moment.
=> Add test to demonstrate support for int-or-string

.dockerignore, Dockerfile, Makefile, README.md
I've not used an automated build as Hub doesn't yet support multi-stage
builds, which makes the builder much simpler.
=> Ability to build/publish a docker image of kubeval

.gitignore, cmd/root.go, kubeval/kubeval.go, kubeval/utils.go, log/log.go
First pass at splitting the monolithic package into separate packages.
This also facilitates the use of kubeval as a library by other tools
which has been discussed a few times.
This is the first pass at this, I want to split the Validate function
down some, and make sure everything is documented. I'll get this merged
quickly to avoid any pain with PRs needing rebasing.
=> Start splitting kubeval up into separate packages

Makefile, cmd/root.go, cmd/version.go, version/version.go
Passing --version will print build information, including the git sha,
tag, architecture/OS details and Go version
Resolves #12
=> Kubeval can now print it's own version information

.travis.yml, Makefile, README.md, acceptance.bats, cmd/root.go, glide.lock, glide.yaml, kubeval/kubeval.go, kubeval/kubeval_test.go
This refactoring moves the display logic out of the kubeval submodule
and into the CLI tool definition. This should make it possible and
hopefully useful to reuse the validator in other tools.
Resolves #10
=> Make kubeval usable as a Go library

.travis.yml, Makefile, README.md
Previously the tar packages had a full directory path in them, which is
just annoying. This communit removes them, so uncompressing the packages
now just gives you the binary.
I've also addedd Zip packages for Windows users.
=> Build 32bit windows binary, and simplify tar paths

README.md
`wget` link appears in two lines. `wget` in one line is easy to use
=> Fix `wget` link position

Makefile
This commit simply adds `CGO_ENABLED=0` to enable a completely static build. This will make the binary run without issue in containers (such as Alpine) and environments that do not bundle `libc` or comparable libraries.
=> Remove dependency on libc

README.md, cmd/root.go
added a commandline option `--filename` to allow overriding the `stdin` filename displayed when accepting manifests from standard input
I have a loop that kinda looks like the below (pseudo)shell example. A Helm template is rendered to a temporary file (greatly simplified here for brevity) so that the test output displays a filename rather than merely `stdin`.
The `--filename` option provided by this PR allows me to delete all the temporary file handling (`mktemp` etc) and simply pipe the output of `helm template ...` directly to `kubeval`.
```
#!/bin/sh
rc=0
cd $HELM_CHART
for values in envs/*yaml; do
for template in templates/*yaml; do
helm template . -x $template -f $values > temporary.yaml
if ! kubeval temporary.yaml ; then
rc=1
fi
rm -f temporary.yaml
done
done
exit $rc
```
The …
=> --filename option to override stdin "filename"

kubeval/kubeval.go
Ignore "---" inline in e.g Configmaps.
This solves #52.
=> Split multi-document yaml files properly

fixtures/multi_valid.yaml, kubeval/kubeval.go
Using `helm template ...` can result in a multi document yaml with empty documents if some resource templates have been disabled:
```
---
---
```
Such a yaml is valid, as it can successfully be installed via `kubectl apply`. kubeval, however,  reports a `* Missing a kind key` for these documents.
This PR makes kubeval report them as valid.
=> empty documents in multi-document yaml files should be valid

Dockerfile, Dockerfile.offline
This will put a symlink in /usr/local/bin to /kubeval so that it's more intuitive for new users that create CI pipelines don't have to know where kubeval is located in the docker container. 
Fixes #72
=> Add kubeval to $PATH to make CI usage more straightforward

acceptance.bats, cmd/root.go, fixtures/comment.yaml, kubeval/kubeval.go, kubeval/kubeval_test.go
Fixes #78.
This enables kubeval to work with optional kubernetes resources in helm charts. See https://github.com/garethr/kubeval/issues/78#issuecomment-394496798 for an example.
Current error with output
```
The document fixtures/blank.yaml appears to be empty
1 error occurred:
* Missing a kind key
```
New success with output
```
The document fixtures/blank.yaml is empty
The document fixtures/comment.yaml is empty
```
=> Validate empty files

cmd/root.go
Checking if stdin is not a char device has false positives. Particularly in
automated environments (such as CI), stdin will not be a char device.
Fixes https://github.com/garethr/kubeval/issues/36
=> Only use stdin if we have no filenames

BUILDING.md, Makefile
this PR uses [pattern rules](https://www.gnu.org/software/make/manual/html_node/Pattern-Rules.html) for matching file names, allowing for a single target to generate multiple targets.
This also fixes the goreleaser URL to point at the right destination.
=> use pattern rules for checksums

Dockerfile, Dockerfile.acceptance, Dockerfile.offline
Was messing around with the project and couldn't build the Dockerfiles. My understanding is that they were not updated when the make targets for building was changed from `make linux` = `/bin/linux/amd64/kubeval` to `make build` = `/bin/kubeval` (during the introduction of GoReleaser?). This PR updates the build step in the Dockerfiles. `make docker`, `make acceptance` and `make docker-offline` now work.
Maybe I'm overlooking something, but anyway here's a PR in case it's a valid fix.
=> Fixed build step in Dockerfiles

kubeval/kubeval.go, kubeval/kubeval_test.go, main.go
When passing in multiple files each schema is downloaded multiple times.
This PR introduces a simple in-memory cache to download required schemas only once during a validation run.
It uses the approach described in https://github.com/xeipuuv/gojsonschema/blob/master/README.md#validation to share load the schema only once.
This reduces the validation time of our ~1k yaml files from 5 mins to ~10s.
=> Basic schema cache

main.go
This modifies the output for files containing empty documents to clarify that whether the file is empty or not, it contains an empty document.
Addresses https://github.com/instrumenta/kubeval/issues/145
=> Clarify output for files containing empty documents

kubeval/kubeval.go, kubeval/kubeval_test.go, main.go
Addresses https://github.com/instrumenta/kubeval/issues/149
This changes the behavior of the `--ignore-missing-schemas` flag. Prior to
this change, the flag prevented validation against schemas for all
documents. The new behavior is to prevent validation against schemas for
any document whose associated schema can not be found. All other
documents are validated against their corresponding schemas.
This also improves the expected behavior of the flag. Prior behavior was
to display a successful message for any document missing its schema. New
behavior will print a warning message that the document was not
validated against a schema. Note that this still returns a success code.
The following demostrates the new behavior against the `valid.yaml`, `invalid.yaml`, and `test_crd.yaml` files …
=> This fixes the --ignore-missing-schemas flag

fixtures/multi_invalid_resources.yaml, kubeval/kubeval.go, kubeval/kubeval_test.go, main.go
This changes the behavior of kubeval such that it no longer halts upon
encountering the first error. Instead, it will log the error, then
continue to process other files/documents.
The previous behavior can be attained by passing the --exit-on-error
flag.
=> Add the --exit-on-error flag

kubeval/kubeval.go, kubeval/kubeval_test.go, main.go
This adds the skip-kinds flag which expects a comma-separated list of
kubernetes resources (labeled by case-sensitive Kind) for which to skip
schema validation. This is useful when validating CRDs for which the
user may not have a schema.
=> Add the --skip-kinds flag

fixtures/multi_valid_source.yaml, kubeval/kubeval.go, kubeval/kubeval_test.go
Helm provides the name of the source template in a comment at the top
of each document, for example:
```yaml
...
```
It is helpful to have this filename in the results when we can detect it.
=> detect Helm source template from comments

go.mod, go.sum, kubeval/kubeval.go, kubeval/kubeval_test.go, kubeval/utils.go
This updates the current YAML library from gopkg.in/yaml.v2 to
sigs.k8s.io/yaml, a wrapper around the former. The k8s library provides
better functionality with regards to unmarshaling a YAML file into a
JSON-friendly data structure.
This commit also includes various cleanups related to the change:
* `convertToStringKeys` has been removed
* functions `determineKind` and `determineAPIVersion` have been replaced
by the more generic `getString`
* functions `in`, `detectLineBreak` and `getString` have been moved to
kubeval/utils.go
Lastly, unit tests have been written for the new `getString` function
=> Update to sigs.k8s.io/yaml

kubeval/kubeval.go
Instead of trying and failing to load the schema multiple times, fetch it only once and remember that it wasn't loadable.
This should improve the kubeval performance if a lot of missing schemas are present.
=> Cache missing schemas

kubeval/config.go, kubeval/kubeval.go, kubeval/kubeval_test.go, main.go
This commit introduces the `Config` object, which contains all the
configuration information that `kubeval.Validate` might need. The default
settings can be obtained by using the `NewDefaultConfig` function.
Functions `Validate` and `ValidateWithCache` have been modified to
accept an optional Config object - if none is provided, the default is
used.
Unit tests have also been updated to reflect these changes.
Note that these changes also pass the newly added acceptance tests in https://github.com/instrumenta/kubeval/pull/157
=> Move configuration into a Config object

kubeval/config.go
Allows schemas to be provided by the `-s` flag. This is consistent with the usage of other "non boolean" flags in this package.
=> add shorthand for providing schemas

main.go
Fixes a logging control flow bug which would result in multiple "output sets" being produced when supplying multiple input files. For example, an invocation with three files and `-o json` would produce three distinct arrays of output, instead of a single array.
**Before:**
```console
⇒  ./bin/kubeval -o json fixtures/valid.yaml fixtures/invalid.yaml
[
{
"filename": "fixtures/valid.yaml",
"kind": "ReplicationController",
"status": "valid",
"errors": []
}
]
[
{
"filename": "fixtures/invalid.yaml",
"kind": "ReplicationController",
"status": "invalid",
"errors": [
"spec.replicas: Invalid type. Expected: [integer,null], given: string"
]
}
]
```
**After:**
```console
⇒  bin/kubeval -o json fixtures/valid.yaml fixtures/valid.yaml
[
{
"filename": "fixtures/valid.yaml",
"kind": …
```
=> Fix stuttering output when supplying multiple files as input

kubeval/config.go, kubeval/kubeval.go, kubeval/kubeval_test.go
This adds an option to kubeval's configuration that allows the use of
additional base URLs to search for schemas. The tool will still prefer
the default repositories, but if a schema cannot be found for a given
YAML document (e.g. a CRD), kubeval will fallback on the secondary URLs.
This implies that schemas must have been pre-generated and hosted at the
secondary URLs.
@garethr I'm not sure why the last PR for this was closed, but anyway, this is a much more polished version of the feature. I'm going to add some documentation on generating schemas sometime tomorrow.
=> Add the --additional-schema-locations flag

acceptance.bats, kubeval/config.go, main.go
Adds a `--quiet` flag for suppressing "non terminal" i.e. `error` or `result` messages from the kubeval logs. 
This will help users who are running kubeval in CI or other automated systems capture only the results they care about.
**Normal output**
```console
⇒  ./bin/kubeval -o json --ignore-missing-schemas fixtures/valid.yaml        
Warning: Set to ignore missing schemas
[
{
"filename": "fixtures/valid.yaml",
"kind": "ReplicationController",
"status": "valid",
"errors": []
}
]
```
**Flag enabled**
```console
⇒  ./bin/kubeval -o json --ignore-missing-schemas --quiet fixtures/valid.yaml
[
{
"filename": "fixtures/valid.yaml",
"kind": "ReplicationController",
"status": "valid",
"errors": []
}
]
```
=> adds a quiet flag

main.go
This will allow the auto-detection of `*.yaml` and `*.yml` files.  
fixes issue #178
=> find yml files also when specified -d flag

docs/index.md
Adds some minor fixes to `docs/index.md`.
This should fix some broken formatting on https://kubeval.instrumenta.dev
@garethr -- what do you use to generate the docs for this app? I would like to verify that my changes work as expected
=> style fixes for markdown docs

kubeval/kubeval.go
Current output:
```
The file fixtures/multi_invalid.yaml contains a valid ReplicationController
The file fixtures/multi_invalid.yaml contains a valid Service
The file fixtures/multi_invalid.yaml contains a valid ReplicationController
The file fixtures/multi_invalid.yaml contains a valid Service
The file fixtures/multi_invalid.yaml contains a valid ReplicationController
5 errors occurred:
* Missing 'kind' value
* Missing 'kind' value
* Missing 'kind' value
* Missing 'kind' value
* Missing 'kind' value
```
With the changes
```
The file fixtures/multi_invalid.yaml contains a valid ReplicationController
The file fixtures/multi_invalid.yaml contains a valid Service
The file fixtures/multi_invalid.yaml contains a valid ReplicationController
The file fixtures/multi_invalid.yaml contains a valid …
```
=> Improve error output

docs/installation.md
Today I installed kubeval and got an error because I tried to use a feature not present in the version pointed in the documentation to install so I made this small change to have docs always updated.
=> Add latest release link to installation docs.

acceptance.bats, main.go
Change the usage message in help output to include the binary name the
command was invoked as, and also adjust it to match kubectl plugin
conventions when the binary name starts with `kubectl-`.
closes #187
=> feat: adjust help when used as kubectl plugin

docs/index.md
Just a fix for two small typos I found in the documentation.
=> Fix yaml/yaml typos in docs/index.md

main.go
This PR adds a `-i`/`--ignored-filename-patterns` flag which allows for specifying a list of filename patterns (regular expressions) to be ignored.
=> Add the '--ignored-filename-patterns' flag.

kubeval/config.go, kubeval/kubeval.go, main.go
Some users are stuck behind corporate HTTP proxies that MITM all traffic and are forced to sacrifice TLS security. This allows those users to use the tool despite the proxy messing with the certificates.
It would be great to continue down this path and provide a more secure option, like what `kubectl` does with the `--certificate-authority` option.
Fixes #197.
=> Add support for --insecure-skip-tls-verify option

main.go
The check to use stdin was incorrectly true when running with no tty
and no files were passed as arguments, even though directories were
passed with -d
Fixes #184
=> Do not use sdtin when directories are passed

fixtures/test_crd.yaml, kubeval/kubeval.go
I've noticed that kubeval was MUCH slower after upgrading from 0.11.0 to 0.14.0. It turns out the schema server kubeval is hitting is very slow in returning 404s (like 15-30 seconds), so if you have a lot of custom resources, you're going to be waiting a long time if there's no caching. While it would be nice to make the server faster, there's no reason to not cache the schema misses.
I noticed that there was a commented-out line that explained why it wasn't done, so I modified a test to reproduce the error mentioned in the comment and then changed the code to fix the nil reference.
=> Cache schema misses if missing schemas allowed

chocolatey/kubeval/kubeval.nuspec, chocolatey/kubeval/tools/chocolateyinstall.ps1
I noticed the Chocolatey package is very out of date and I ran into issues trying to use `kubeval` from it. This seems to me like the minimum set of changes required to bring it up-to-date here, but I don't know what updates are required to update it at https://chocolatey.org/packages/kubeval
=> Updating Chocolatey package

fixtures/list_invalid.yaml, fixtures/list_valid.yaml, kubeval/kubeval.go, kubeval/kubeval_test.go
This PR adds support for yaml files with a list of k8s objects in them, for example:
```
apiVersion: v1
kind: List
items:
- apiVersion: v1
kind: ConfigMap
metadata:
name: cf-one
- apiVersion: v1
kind: ConfigMap
metadata:
name: cf-two
```
=> Add support for a list of k8s objects

kubeval/kubeval.go, kubeval/output.go, kubeval/utils.go
This assists with finding issues in large collections of manifests. This is especially useful when used in conjunction with kustomize where the manifests are transformed and piped.
=> Adds qualified names to output

kubeval/config.go, kubeval/kubeval.go, kubeval/kubeval_test.go
Adds the ability to specify a comma-delimited list of prohibited Kubernetes resource Kinds.
```
kubeval --exit-on-error --reject-kinds "Secret" -d ./workloads/example
PASS - workloads/example/deployment.yaml contains a valid Deployment
PASS - workloads/example/env.yaml contains a valid ConfigMap
ERR  - Prohibited resourse kind 'Secret' in workloads/example/secret.yaml
```
Fixes #225
=> Add --reject-kinds flag

main.go
Currently, piping a manifest with very long lines subtly breaks kubeval. The `bufio.Scanner` used is not checked for errors after use, and for lines longer than 64k (https://github.com/golang/go/blob/go1.14/src/bufio/scan.go#L79) this means missing an `ErrTooLong`. Since the error is never checked, kubeval assumes the full input has been read, and validates whatever it managed to read.
We ran into this because of a ConfigMap with a `binaryData` segment of a couple hundred kilobytes.
This PR removes the Scanner and just uses `io.Copy` instead.
ping @garethr
=> Fix long lines not working over stdin

fixtures/duplicates-non-namespaced.yaml, fixtures/duplicates-skipped-kinds.yaml, fixtures/duplicates-with-namespace-default.yaml, fixtures/duplicates-with-namespace.yaml, fixtures/duplicates.yaml, fixtures/same-kind-different-api.yaml, fixtures/same-object-different-namespace-default.yaml, fixtures/same-object-different-namespace.yaml, go.mod, go.sum, kubeval/config.go, kubeval/kubeval.go, kubeval/kubeval_test.go, kubeval/utils.go
Introduces `-n/--default-namespace` to specify which namespace a resource would be assigned if none is explicitly defined in the manifest. Exhaustively tested.
=> Detect duplicate resources (same [API version, kind, namespace, name])

main.go
This PR changes the `-i/--ignored-filename-patterns` flag to `-i/--ignored-path-patterns`. As it allows more advanced configuration which files should be ignored. 
It works in a similar way like previously, so it accepts a list of directory patterns (regular expressions) to be ignored.
I've encountered difficulties with the previous solution when I wanted to configure the Github Actions for a repository used for GitOps approach. I wasn't able to run validation on all yaml files in any directory with exception of the `.github` directory. 
Now it's possible with passing `ignored_path_patterns="^\.github"`.
=> Changed ignored_filename_patterns to ignored_path_patterns

docs/contrib.md
it is way faster to run kubeval once with the files as arguments
or using `-d`
=> find + exec is very slow

kubeval/output.go, kubeval/output_test.go
Playing around with tap-to-junit vlaidations I found that the only safe way
to get the skips parsed was to use capitalized `# SKIP` with the space after the description.
Technically lowercase seems to be allowed but the majority of the schema's
examples show capitalized.
https://testanything.org/tap-version-13-specification.html
In the schema it also says any explanation of why it was skipped should go
after the `# SKIP`, but the description of the test still goes to the left.
I wasn't sure what all would be necessary but it would be kewl to have the
returned status value for the reason they were skipped map to a string
to append to the line.
=> fix: TAP Schema treats SKIP as a directive, at the end of the line

kubeval/output.go
This fixes the line count being incorrect on the tap output.
The previous code would work but only if the last file was the file that had an error.
=> Fix line count for errors on tap output

.goreleaser.yml
Closes https://github.com/instrumenta/kubeval/issues/291
This config makes GoReleaser _explicitly_ build `arm64` binaries and tarballs. The architecture has been added to the default list recently and releasing using an older version wouldn't include it (see https://github.com/goreleaser/goreleaser/commit/2edebf0029e8c5a873947306ee892f089438795f).
=> Update GoReleaser config to build arm binaries and tarballs explicitly
